# Generated by Django 5.2 on 2025-04-24 03:57

import blog.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_journalentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this entry was first created'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='image',
            field=models.ImageField(blank=True, help_text='An image to attach to your journal entry', null=True, upload_to=blog.models.user_journal_image_path),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_private',
            field=models.BooleanField(default=True, help_text='Whether this entry is private or can be viewed by others'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this entry was last updated'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='weather',
            field=models.CharField(blank=True, choices=[('☀️ Sunny', 'Sunny'), ('🌤️ Partly Cloudy', 'Partly Cloudy'), ('☁️ Cloudy', 'Cloudy'), ('🌧️ Rainy', 'Rainy'), ('⛈️ Stormy', 'Stormy'), ('❄️ Snowy', 'Snowy'), ('🌫️ Foggy', 'Foggy')], help_text='The weather on this day', max_length=50),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='content',
            field=models.TextField(help_text='Main content of the journal entry'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the journal entry'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, choices=[('😊 Happy', 'Happy'), ('😐 Neutral', 'Neutral'), ('😔 Sad', 'Sad'), ('😡 Angry', 'Angry'), ('😴 Tired', 'Tired'), ('🤩 Excited', 'Excited')], help_text='How you were feeling', max_length=50),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='tags',
            field=models.CharField(blank=True, help_text='Space-separated tags to categorize entries', max_length=200),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(help_text='Title of the journal entry', max_length=200),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(help_text='The user who created this journal entry', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
